---
title: "Template UNM reveal.js"
format: 
  unm-revealjs:
    slide-number: c/t
author:
  - name: Your Name
    orcid: 0000-0000-0000-0000
    email: alias@email.com
    # affiliations: Your Institution
# date: last-modified 
---

## Example slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Section Slide {.section-slide}

This is a section slide, which is a slide that contains only a section title.

- This is useful for breaking up the presentation into sections.

## Additional theme classes

### Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

### Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)


## Code blocks

### R code

```{r}
#| echo: true
# This is an R code block
x <- rnorm(100)
y <- 2*x + rnorm(100)
summary(lm(y ~ x))
``` 